In [1]:
import os
code_path = os.path.dirname(os.path.abspath(".")).rsplit("/",1)[0]
import sys
sys.path.append(code_path + '/model_code')

import numpy as np
import pandas as pd
import torch
from dgl.dataloading import GraphDataLoader
from Dataloader.dataloader import LeadOptDataset
from utilis.Interaction_atoms import GetAtomPairAndType,read_mol2_file_withoutH,read_mol2_file_H
from utilis.utilis import pkl_load


In [2]:
ligand1_dir =f"{code_path}/data/test_set_fep_graph_rmH_I/Jnk1/Jnk1_18660-1.pkl"
ligand2_dir =f"{code_path}/data/test_set_fep_graph_rmH_I/Jnk1/Jnk1_18660-1.pkl"
pocket_dir = f"{code_path}/data/test_set_fep_graph_rmH_I/Jnk1/pocket.pkl"

graph1 = pkl_load(ligand1_dir)
graph2 = pkl_load(ligand2_dir)
pock = pkl_load(pocket_dir)


In [3]:
model = torch.load(f"{code_path}/PBCNet.pth",map_location="cpu")

In [4]:
logits,_,att1,att2= model(graph1,graph2, pock)


In [5]:
att2_processed = att1.mean(dim=1)
att2_processed.shape

torch.Size([1476, 1])

In [6]:
graph1.edata["attention_weight"].shape

torch.Size([1476, 1])

In [7]:
graph1.num_nodes()

32

In [8]:
ligand1_dir =f"{code_path}/data/test_set_fep_graph_rmH_I/Jnk1/Jnk1_18660-1.pkl"
ligand2_dir =f"{code_path}/data/test_set_fep_graph_rmH_I/Jnk1/Jnk1_18660-1.pkl"
pocket_dir = f"{code_path}/data/test_set_fep_graph_rmH_I/Jnk1/pocket.pkl"

graph1 = pkl_load(ligand1_dir)
graph2 = pkl_load(ligand2_dir)
pock = pkl_load(pocket_dir)

In [9]:
graph1.num_nodes()

391

In [10]:
GetAtomPairAndType(f"{code_path}/data/FEP1/Jnk1/Jnk1_18660-1.sdf")

([[12, 'GLU109O'],
  [18, 'MET111H'],
  [24, 'ILE32CB'],
  [25, 'ILE32CB'],
  [24, 'ILE32CG2'],
  [25, 'ILE32CG2'],
  [13, 'VAL40CG2'],
  [10, 'ALA53CB'],
  [20, 'LEU110CD2'],
  [27, 'LEU110CD2'],
  [19, 'MET111CB'],
  [0, 'LEU168CG'],
  [13, 'LEU168CG'],
  [13, 'LEU168CD1'],
  [0, 'LEU168CD2'],
  [4, 'LEU168CD2'],
  [13, 'LEU168CD2'],
  [0, 'ASP169CB']],
 ['Hbond',
  'Hbond',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob'])

In [11]:
mol2_file_pock = read_mol2_file_withoutH(f"{code_path}/data/FEP1//Jnk1/pocket.mol2")

# 12-position

In [12]:
graph1.in_edges(12, form='all')

(tensor([ 11, 102, 135, 137, 138, 178, 180, 202, 204, 205, 206, 207, 208, 210,
         211, 368, 369]),
 tensor([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12]),
 tensor([  26,  976,  988,  990,  998, 1018, 1024, 1026, 1028, 1032, 1040, 1048,
         1054, 1058, 1064, 1404, 1428]))

In [13]:
graph1.in_edges(12,form='all')[0]-32

tensor([-21,  70, 103, 105, 106, 146, 148, 170, 172, 173, 174, 175, 176, 178,
        179, 336, 337])

In [14]:
len(graph1.in_edges(12,form='all')[0])

17

In [15]:
mol2_file_pock[[11,  70, 103, 105, 106, 146, 148, 170, 172, 173, 174, 175, 176, 178,
        179, 336, 337]]

array([['25', 'C', '29.2120', '7.7870', '35.5650', 'C.2', '2', 'PRO31',
        '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['140', 'CG2', '22.5120', '10.9090', '35.7890', 'C.3', '11',
        'VAL40', '0.0000', 'DICT'],
       ['212', 'CA', '20.0380', '7.8230', '37.8160', 'C.3', '17',
        'ALA53', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['214', 'O', '18.8010', '9.7390', '38.4990', 'O.2', '17', 'ALA53',
        '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['215', 'CB', '19.7940', '8.1240', '36.3290', 'C.3', '17',
        'ALA53', '0.0000', 'DICT'],
       ['299', 'CG1', '13.9020', '8.3600', '32.1460', 'C.3', '22',
        'ILE86', '0.0000', 'DICT'],
       ['301', 'CD1', '15.4250', '8.2380', '32.0060', 'C.3', '22',
        'ILE86', '0.0000', 'DICT'],
       ['357', 'C', '15.3330', '7.7140', '37.2480', 'C.2', '26',
        'MET108', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['359', 'CB', '15.0160', '10.1770', '36.4910', 'C.3', '26',
        'MET108', '0.0000', 'DICT'],
       ['360', '

In [16]:
att2_processed[graph1.in_edges(12, form='all')[2]]

tensor([[0.1209],
        [0.0635],
        [0.0555],
        [0.0683],
        [0.0242],
        [0.0564],
        [0.0673],
        [0.0667],
        [0.0479],
        [0.0114],
        [0.0312],
        [0.0541],
        [0.0603],
        [0.0406],
        [0.1084],
        [0.0633],
        [0.0601]], grad_fn=<IndexBackward0>)

# 18-position

In [17]:
graph1.in_edges(18, form='all')

(tensor([ 17, 211, 217, 218, 219, 220, 221, 222, 224, 225, 226, 227, 228, 229,
         230, 233, 244, 327, 328, 329]),
 tensor([18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18, 18,
         18, 18]),
 tensor([  36, 1066, 1068, 1074, 1078, 1080, 1086, 1096, 1118, 1140, 1150, 1158,
         1170, 1186, 1192, 1198, 1290, 1364, 1378, 1388]))

In [18]:
graph1.in_edges(18,form='all')[0]-32

tensor([-15, 179, 185, 186, 187, 188, 189, 190, 192, 193, 194, 195, 196, 197,
        198, 201, 212, 295, 296, 297])

In [19]:
len(graph1.in_edges(18,form='all')[0])

20

In [20]:
mol2_file_pock[[17, 179, 185, 186, 187, 188, 189, 190, 192, 193, 194, 195, 196, 197,
        198, 201, 212, 295, 296, 297]]


array([['38', 'CA', '27.6520', '7.7590', '33.6350', 'C.3', '3', 'ILE32',
        '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['375', 'O', '16.9270', '6.7460', '34.7530', 'O.2', '27',
        'GLU109', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['387', 'N', '16.8030', '4.4820', '34.8780', 'N.am', '28',
        'LEU110', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['388', 'CA', '18.1070', '4.2020', '34.2890', 'C.3', '28',
        'LEU110', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['389', 'C', '17.9850', '2.9390', '33.4290', 'C.2', '28',
        'LEU110', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['390', 'O', '17.5810', '1.8930', '33.9370', 'O.2', '28',
        'LEU110', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['391', 'CB', '19.1510', '4.1040', '35.4240', 'C.3', '28',
        'LEU110', '0.0000', 'DICT'],
       ['392', 'CG', '20.6290', '4.1710', '34.9800', 'C.3', '28',
        'LEU110', '0.0000', 'DICT'],
       ['394', 'CD2', '21.1540', '2.8560', '34.3760', 'C.3', '28',
        'LEU110', '

In [21]:
att2_processed[graph1.in_edges(18, form='all')[2]]

tensor([[0.0794],
        [0.0316],
        [0.0409],
        [0.0430],
        [0.0714],
        [0.0422],
        [0.0289],
        [0.0358],
        [0.0316],
        [0.2104],
        [0.0435],
        [0.0305],
        [0.0286],
        [0.0549],
        [0.0425],
        [0.0365],
        [0.0486],
        [0.0349],
        [0.0364],
        [0.0284]], grad_fn=<IndexBackward0>)

# 5-position

In [22]:
graph1.in_edges(5, form='all')

(tensor([  4,   6,  53,  55,  57, 101, 304, 370]),
 tensor([5, 5, 5, 5, 5, 5, 5, 5]),
 tensor([   8,   11,  830,  864,  902,  952, 1342, 1444]))

In [23]:
graph1.in_edges(5,form='all')[0]-32

tensor([-28, -26,  21,  23,  25,  69, 272, 338])

In [24]:
len(graph1.in_edges(5,form='all')[0])

8

In [25]:
mol2_file_pock[[-28, -26,  21,  23,  25,  69, 272, 338]]

array([['681', 'CD1', '12.5760', '10.5960', '22.6580', 'C.3', '46',
        'ILE167', '0.0000', 'DICT'],
       ['694', 'CA', '15.8840', '12.4220', '28.1260', 'C.3', '47',
        'LEU168', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['42', 'CG1', '25.1090', '8.1920', '34.0700', 'C.3', '3', 'ILE32',
        '0.0000', 'DICT'],
       ['44', 'CD1', '23.6790', '7.6360', '34.0330', 'C.3', '3', 'ILE32',
        '0.0000', 'DICT'],
       ['57', 'CA', '27.8760', '11.2850', '32.1250', 'C.3', '4', 'GLY33',
        '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['139', 'CG1', '24.1320', '11.9280', '34.1360', 'C.3', '11',
        'VAL40', '0.0000', 'DICT'],
       ['557', 'O', '22.7370', '11.9420', '26.1180', 'O.2', '39',
        'SER155', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['700', 'CD2', '19.4750', '11.0020', '29.0780', 'C.3', '47',
        'LEU168', '0.0000', 'DICT']], dtype='<U20')

In [26]:
att2_processed[graph1.in_edges(5, form='all')[2]]

tensor([[0.1868],
        [0.1931],
        [0.0971],
        [0.0960],
        [0.1061],
        [0.1171],
        [0.0871],
        [0.1167]], grad_fn=<IndexBackward0>)