In [1]:
import os
code_path = os.path.dirname(os.path.abspath(".")).rsplit("/",1)[0]
import sys
sys.path.append(code_path + '/model_code')

import numpy as np
import pandas as pd
import torch
from dgl.dataloading import GraphDataLoader
from Dataloader.dataloader import LeadOptDataset
from utilis.Interaction_atoms import GetAtomPairAndType,read_mol2_file_withoutH,read_mol2_file_H
from utilis.utilis import pkl_load


In [2]:
code_path

'/home/yujie/code230118'

In [3]:
ligand1_dir =f"{code_path}/data/test_set_fep_graph_rmH_I/Thrombin/Thrombin_6a.pkl"
ligand2_dir =f"{code_path}/data/test_set_fep_graph_rmH_I/Thrombin/Thrombin_6a.pkl"
pocket_dir = f"{code_path}/data/test_set_fep_graph_rmH_I/Thrombin/pocket.pkl"

graph1 = pkl_load(ligand1_dir)
graph2 = pkl_load(ligand2_dir)
pock = pkl_load(pocket_dir)

In [4]:
model = torch.load(f"{code_path}/PBCNet.pth",map_location="cpu")


In [5]:
logits,_,att1,att2 = model(graph1,graph2, pock)


In [6]:
att2_processed = att1.mean(dim=1)
att2_processed.shape

torch.Size([1886, 1])

In [7]:
graph1.edata["attention_weight"].shape

torch.Size([1886, 1])

In [8]:
graph1.num_nodes()

30

In [9]:
ligand1_dir =f"{code_path}/data/test_set_fep_graph_rmH_I/Thrombin/Thrombin_6a.pkl"
ligand2_dir =f"{code_path}/data/test_set_fep_graph_rmH_I/Thrombin/Thrombin_6a.pkl"
pocket_dir = f"{code_path}/data/test_set_fep_graph_rmH_I/Thrombin/pocket.pkl"

graph1 = pkl_load(ligand1_dir)
graph2 = pkl_load(ligand2_dir)
pock = pkl_load(pocket_dir)

In [10]:
graph1.num_nodes()

486

In [11]:
GetAtomPairAndType(f"{code_path}/data/FEP1/Thrombin/Thrombin_6a.sdf")

([[8, 'SER214O'],
  [10, 'GLY216O'],
  [3, 'GLY216H'],
  [14, 'TRP215CD2'],
  [14, 'TRP215CG'],
  [9, 'TYR60ACE1'],
  [9, 'TYR60ACE2'],
  [6, 'TRP60DCZ3'],
  [6, 'TRP60DCH2'],
  [9, 'TRP60DCH2'],
  [18, 'LEU99CD1'],
  [20, 'LEU99CD1'],
  [6, 'LEU99CD2'],
  [9, 'LEU99CD2'],
  [14, 'ILE174CD1'],
  [16, 'ILE174CD1'],
  [21, 'ALA190CB'],
  [23, 'ALA190CB'],
  [27, 'ALA190CB'],
  [23, 'VAL213CG1'],
  [25, 'VAL213CG1'],
  [27, 'VAL213CG1'],
  [16, 'TRP215CB'],
  [16, 'TRP215CG'],
  [18, 'TRP215CG'],
  [16, 'TRP215CD2'],
  [16, 'TRP215CE3']],
 ['Hbond',
  'Hbond',
  'Hbond',
  'PiPi',
  'PiPi',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob',
  'HPhob'])

In [12]:
mol2_file_pock = read_mol2_file_withoutH(f"{code_path}/data/FEP1/Thrombin/pocket.mol2")

# 8-position

In [13]:
graph1.in_edges(8, form='all')

(tensor([  4,  12,  63,  64,  65, 340, 341, 367, 368, 371, 372, 373, 375, 385,
         473]),
 tensor([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8]),
 tensor([  16,   25, 1132, 1142, 1154, 1456, 1464, 1512, 1534, 1546, 1570, 1594,
         1642, 1716, 1862]))

In [14]:
graph1.in_edges(8,form='all')[0]-30

tensor([-26, -18,  33,  34,  35, 310, 311, 337, 338, 341, 342, 343, 345, 355,
        443])

In [15]:
len(graph1.in_edges(8,form='all')[0]-30)

15

In [16]:
mol2_file_pock[[-26, -18, 33,  34,  35, 310, 311, 337, 338, 341, 342, 343, 345,
        355]]

array([['787', 'CB', '15.7170', '-7.9730', '28.6310', 'C.3', '53',
        'PHE227', '0.0000', 'DICT'],
       ['804', 'CA', '15.1530', '-3.6090', '27.0900', 'C.3', '54',
        'TYR228', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['65', 'CD2', '19.1140', '-8.9800', '18.3870', 'C.2', '5',
        'HIS57', '0.0000', 'DICT'],
       ['66', 'CE1', '18.2050', '-7.3630', '19.5340', 'C.2', '5',
        'HIS57', '0.0000', 'DICT'],
       ['67', 'NE2', '17.9130', '-8.4380', '18.8090', 'N.2', '5',
        'HIS57', '0.0000', 'DICT'],
       ['589', 'CB', '15.0710', '-7.4200', '17.4410', 'C.3', '38',
        'SER195', '0.0000', 'DICT'],
       ['590', 'OG', '15.0170', '-8.5450', '18.2950', 'O.3', '38',
        'SER195', '0.0000', 'DICT'],
       ['647', 'C', '16.8910', '-7.8420', '23.2850', 'C.2', '43',
        'SER214', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['648', 'O', '17.4350', '-8.3620', '22.3110', 'O.2', '43',
        'SER214', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['656', 'N', '16.

In [17]:
att2_processed[graph1.in_edges(8, form='all')[2]]

tensor([[0.1071],
        [0.1059],
        [0.0493],
        [0.0565],
        [0.0472],
        [0.0616],
        [0.0372],
        [0.0714],
        [0.0764],
        [0.0790],
        [0.0570],
        [0.0435],
        [0.0497],
        [0.0839],
        [0.0743]], grad_fn=<IndexBackward0>)

In [18]:
len(att2_processed[graph1.in_edges(8, form='all')[2]])

15

# 10-position

In [19]:
graph1.in_edges(10, form='all')

(tensor([  7, 385, 387, 388, 389, 390, 398]),
 tensor([10, 10, 10, 10, 10, 10, 10]),
 tensor([  20, 1718, 1766, 1784, 1800, 1802, 1806]))

In [20]:
graph1.in_edges(10,form='all')[0]-30

tensor([-23, 355, 357, 358, 359, 360, 368])

In [21]:
mol2_file_pock[[-23, 355, 357, 358, 359, 360, 368]]

array([['790', 'CD2', '16.1340', '-8.2190', '31.1190', 'C.ar', '53',
        'PHE227', '0.0000', 'DICT'],
       ['680', 'N', '14.4810', '-11.7160', '24.8690', 'N.am', '45',
        'GLY216', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['682', 'C', '13.6710', '-13.9000', '25.5000', 'C.2', '45',
        'GLY216', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['683', 'O', '14.0550', '-14.3510', '24.4180', 'O.2', '45',
        'GLY216', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['687', 'N', '13.3560', '-14.6790', '26.5470', 'N.am', '46',
        'GLU217', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['688', 'CA', '13.3350', '-16.1430', '26.5250', 'C.3', '46',
        'GLU217', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['702', 'N', '11.8100', '-16.7300', '24.7240', 'N.am', '47',
        'GLY219', '0.0000', 'BACKBONE|DICT|DIRECT']], dtype='<U20')

In [22]:
att2_processed[graph1.in_edges(10, form='all')[2]]

tensor([[0.2415],
        [0.1149],
        [0.0856],
        [0.2349],
        [0.1160],
        [0.0900],
        [0.1172]], grad_fn=<IndexBackward0>)

# 3-position

In [23]:
graph1.in_edges(3, form='all')

(tensor([  2, 368, 371, 372, 373, 374, 375, 376, 378, 381, 385, 386, 387, 388,
         389]),
 tensor([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]),
 tensor([  10, 1528, 1544, 1566, 1592, 1614, 1636, 1660, 1676, 1696, 1710, 1742,
         1762, 1780, 1798]))

In [24]:
graph1.in_edges(3,form='all')[0]-30

tensor([-28, 338, 341, 342, 343, 344, 345, 346, 348, 351, 355, 356, 357, 358,
        359])

In [25]:
mol2_file_pock[[-28, 338, 341, 342, 343, 344, 345, 346, 348, 351, 355, 356, 357, 358,
        359]]

array([['785', 'C', '14.6960', '-6.0380', '27.3280', 'C.2', '53',
        'PHE227', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['648', 'O', '17.4350', '-8.3620', '22.3110', 'O.2', '43',
        'SER214', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['656', 'N', '16.2040', '-8.5340', '24.2100', 'N.am', '44',
        'TRP215', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['657', 'CA', '16.0580', '-9.9940', '24.1870', 'C.3', '44',
        'TRP215', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['658', 'C', '14.8900', '-10.4570', '25.0670', 'C.2', '44',
        'TRP215', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['659', 'O', '14.4060', '-9.7000', '25.9070', 'O.2', '44',
        'TRP215', '0.0000', 'BACKBONE|DICT|DIRECT'],
       ['660', 'CB', '17.3830', '-10.6920', '24.5860', 'C.3', '44',
        'TRP215', '0.0000', 'DICT'],
       ['661', 'CG', '17.9640', '-10.3870', '25.9390', 'C.ar', '44',
        'TRP215', '0.0000', 'DICT'],
       ['663', 'CD2', '17.7220', '-11.0440', '27.2230', 'C.ar', '44',
  

In [26]:
att2_processed[graph1.in_edges(3, form='all')[2]]

tensor([[0.1101],
        [0.0660],
        [0.0520],
        [0.0745],
        [0.0661],
        [0.0658],
        [0.0353],
        [0.0553],
        [0.0536],
        [0.0428],
        [0.1924],
        [0.0482],
        [0.0589],
        [0.0328],
        [0.0462]], grad_fn=<IndexBackward0>)